name: Django CI

on:
  release:
    types: [published]

jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"

      - name: Debug version
        id: debug
        run: echo ${{ steps.get_version.outputs.VERSION }}

      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check directory
        run: |
            ls
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.GCP_IP}}
          username: arcreator07
          key: ${{secrets.GCP_PRIVATE_KEY}}
          port: 22
          run: |
            pwd
            ls -al
          script: | 
            /bin/sh ./deploy.sh ${{ steps.get_version.outputs.VERSION }}
